---
title: "Simple document"
output: html_document
---

```{r}
library(tidyverse)
library(readxl) ## we are loading this to use read_excel
library(haven)
```

##Read in some data

Read in litters data set.

```{r}
litters_df = read.csv("./data_import_examples/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df) ##loads the janitor package without using library function - this clean names function just cleans up the names and makes them snake case
```

##Take a look at the data
Printing of the console
```{r}
litters_df ##outputs the data frame
```

```{r}
head(litters_df) ##gives the first 6 rows
tail(litters_df)
```

```{r}
skimr::skim(litters_df) #tells you info on values that are missing, standard deviation, etc.
```
### Use the view() function to view in a different window

## Options to read csv

```{r}
litters_df = read.csv("./data_import_examples/FAS_litters.csv", skip = 10, na = c("", "NA", 999)) #na = c() addresses missing values
```
### Look at help file to learn more about the things you can include

## Other file formats

Read in an excel file.

```{r}
mlb_df = read_excel("./data_import_examples/mlb11.xlsx")
#when you look at the help feature for read excel, you will see that there are options where you need to specify the sheet you are using if you have multiple sheets, and there is a range function
```

Read in a SAS file.

```{r}
pulse_df = read_sas("./data_import_examples/public_pulse_data.sas7bdat")
```

## Comparison with Base R

## Exporting Data

Export the mlb sub-table

```{r}
write_csv(mlb_df, "./data_import_examples/mlb_subtable") #This exports the data and gives it a location where it will be saved and the name of the new exported thingy
```

